### ISSUE TITLE
Select and deselect J2534 interface

### ISSUE THREAD

**Issue by N0cynym** [jglim/CaesarSuite#2]
After selecting interface it's possible to change my interface if Diogenes.exe is running.

**Problems:**

1.  When I exit Diogenes.exe it will not deselect my interface.
2.  My J2534 devices are not working as well as I thought (PCANPT32.dll & AbrPT32.dll). 
Every single time I'm trying to connect an ecu I have differnt faults from PassThru DLL.
Is it possible to give me food for my thoughts?

Thanks for your amazing work!

**Comment by jglim** [comment]
Hi N0cynym, 

Thank you for your report. Regrettably, I do not have a clear answer for you at this time. 

My application references an external library, J2534-Sharp, to interact with the PassThru DLL. The library will [automatically deselect your interface](https://github.com/BrianHumlicek/J2534-Sharp/blob/84a2bc272806d80a655628f12d303c06581c55f2/Src/Device.cs#L122) when the application closes. I have looked through it and I believe that it is unlikely to be the source of the issue.

My existing PassThru device does not have any issues when repeatedly closed and opened. Perhaps if the [OpenPort driver](https://www.tactrix.com/downloads/openport2_setup_1024943.exe) does not work for you, there might be some other underlying issue (e.g. missing MSVC runtime?)

**Comment by N0cynym** [comment]
Ok no problem.
Is the J2534 lib sourced from [here](https://github.com/BrianHumlicek/J2534-Sharp)?
I will post my fixes if I have found out why my J2534 libs are having faults.

**Comment by jglim** [comment]
Yes, specifically from NuGet at https://www.nuget.org/packages/J2534-Sharp/1.0.0-CI00026 . Thanks for taking your time to try out Diogenes.

**Comment by jglim** [comment]
Added a disconnect feature in https://github.com/jglim/CaesarSuite/commit/061bcfdf01953a0b85dbdd4f9322aac73a4bac87 (Release: https://github.com/jglim/CaesarSuite/releases/tag/v1.4.4 ). Thanks for your patience.
