### ISSUE TITLE
Wiki Images

### ISSUE THREAD

**Issue by jglim** [jglim/CaesarSuite#23]
This issue is intended to store images to be used in the repo's wiki, and is intentionally closed.

**Comment by jglim** [comment]
![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832363630353530375f636166613438356265315f682e6a7067](https://user-images.githubusercontent.com/1116555/104668990-249a8180-5714-11eb-9d72-d453527685c5.jpg)

![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832363530393331365f656431376636306635335f682e6a7067](https://user-images.githubusercontent.com/1116555/104668993-25331800-5714-11eb-958d-becd81a449ce.jpg)

![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832363530393333315f306632303234373032345f6d2e6a7067](https://user-images.githubusercontent.com/1116555/104668994-25cbae80-5714-11eb-8337-fae97295be0a.jpg)

![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832363530393332315f643531386264333132372e6a7067](https://user-images.githubusercontent.com/1116555/104668998-26644500-5714-11eb-9a97-c769be904dde.jpg)

![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832353132373431385f333432333161613535625f7a2e6a7067](https://user-images.githubusercontent.com/1116555/104669000-26644500-5714-11eb-837f-c15c91c89776.jpg)

![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832353736313930335f343661393463303436375f682e6a7067](https://user-images.githubusercontent.com/1116555/104669002-26fcdb80-5714-11eb-9383-68c7bb50af3f.jpg)

![68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f35303832363630353537325f663639393930636234655f682e6a7067](https://user-images.githubusercontent.com/1116555/104669146-6dead100-5714-11eb-8015-54146dd0c79a.jpg)

**Comment by N0cynym** [comment]
This image point on the J2534 usage in the basic workflow.
![BasicWorkflowCaesarSuiteObdJ2534](https://user-images.githubusercontent.com/75754060/104685365-2c016100-56fb-11eb-825e-d2e962f4390e.png)

**Comment by Feezex** [comment]
![trace](https://user-images.githubusercontent.com/75809563/104846298-7a248900-58e2-11eb-9996-621f9dbc7f4e.jpg)
![ECU2](https://user-images.githubusercontent.com/75809563/104846299-7b55b600-58e2-11eb-86aa-93c731b61bb3.jpg)

**Comment by N0cynym** [comment]
![Diogenes_250x250px](https://user-images.githubusercontent.com/75754060/106656633-38126d00-659b-11eb-8d4e-3af98afc60e4.png)

**Comment by N0cynym** [comment]
Need module images in 250x250px to use them in module description please.
