### ISSUE TITLE
contextMenuLimit in VCForm

### ISSUE THREAD

**Issue by N0cynym** [jglim/CaesarSuite#3]
Is it possible to offer a option to set this [limit](https://github.com/jglim/CaesarSuite/blob/main/Caesar/Diogenes/VCForm.cs#L278)?
For example vgsnag2 provides a lot of possible VC and to verify the VC function it whould be nice to test, program and verfiy the string on test bench with vgnag2 device and Monaco/Vediamo.

Or should I compile it local with higher [limit](https://github.com/jglim/CaesarSuite/blob/main/Caesar/Diogenes/VCForm.cs#L278)?

**Comment by jglim** [comment]
Hi N0cynym, 

I took a look at vgsnag2, and indeed there is too many entries to reasonably show in a context menu. I've [added](https://github.com/jglim/CaesarSuite/commit/bbedb162d7afe55ddc36eedd93286be946b1b3d5) a selection dialog (with scrollbars) which will not be constrained by the context menu limit. Thanks for pointing this out.

![image](https://user-images.githubusercontent.com/1116555/102199102-2b0fc080-3efe-11eb-834b-21681ce9bfd6.png)

If this is still insufficient, let me know and I will reopen the issue and try to find a different solution.

**Comment by N0cynym** [comment]
Is it possible to add `txtFilter` for search in Form?

**Comment by jglim** [comment]
Sure - added in v1.3.2 https://github.com/jglim/CaesarSuite/releases/tag/v1.3.2

**Comment by N0cynym** [comment]
Can we set [this ](https://github.com/jglim/CaesarSuite/blob/87dc8a1d1c02446648f1bcb92e9b5b646ebd6ee9/Caesar/Diogenes/Forms/VCForm.cs#L290)higher?
I mean you can find the segments with the search but I think it's better to show them all.

**Comment by jglim** [comment]
I might have to add a separate settings page that also includes a configurable limit (individual preference: the current limit is quite comfortable for me). This is definitely doable, but might take a while as I would want to aggregate a bunch of user settings before adding a preferences page.

**Comment by N0cynym** [comment]
Definitely a better way!
Thanks for informing about this plan.
