### ISSUE TITLE
Standalone trace log window for ECU communications

### ISSUE THREAD

**Issue by jglim** [jglim/CaesarSuite#6]
Diogenes should have a separate log specifically for ECU communications only, essentially replicating the "Show Trace" feature in Vediamo.

(suggestion from @N0cynym)

**Comment by jglim** [comment]
Implemented in https://github.com/jglim/CaesarSuite/commit/3bc32275a572e38185d7f51206483ae92f2e0d38

**Comment by Feezex** [comment]
is it possible to improve this feature?
1. Extended raw data {id : dlc : data} by configuring trace window.
2. Standalone functionality requires Speed\Start\Stop buttons to start trace withought any cbf loaded. So it can act like Can Hacker.

**Comment by jglim** [comment]
(1) Seems straightforward and should be OK. DLC in this iso15765 context is a bit ambiguous, but I will use the pure data length for now (no address prefix). Something like `00 00 07 E8 50 01` would be dlc = 2. I'll try to slip this along with the next update, whenever that might be.

(2) The current implementation makes it difficult to add this in, as it is tightly linked to a loaded CBF. I am still (very slowly) working on a significant rewrite of this project that, among other changes, depends on a set of communication-parameters instead of a CBF.
